dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - xvfb
      - google-chrome-stable
language: node_js
node_js:
  - "7"
matrix:
  include:
    - os: osx
    - os: linux
    - os: windows

before_install:
    # setting the path for phantom.js 2.0.0
    - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - "npm config set spin false"
    - "npm install -g npm@^2"
install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm install
script:
    - npm run build
